### ISSUE TITLE
Update error to 14.5.0.1

### ISSUE THREAD

**Issue by sq8mvy** [chan-sccp/sccp_manager#62]
I have upgraded to the latest version 14.5.0.1 of sccp_manager.
I get errors and the installation fails:

root@odroidn2:~# fwconsole ma upgrade sccp_manager
No repos specified, using: [standard,stable] from last GUI settings

Starting module download from https://github.com/chan-sccp/sccp_manager/archive/refs/tags/v14.5.0.1.tar.gz ...
Processing 
Downloading...
 143/143 [============================] 100%
Finished downloading
Extracting...Done
Module https://github.com/chan-sccp/sccp_manager/archive/refs/tags/v14.5.0.1.tar.gz successfully downloaded
Updating tables sccpdevice, sccpline, sccpbuttonconfig, sccpdevmodel, sccpuser, sccpsettings...Done
PHP Fatal error:  During class fetch: Uncaught Whoops\Exception\ErrorException: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/admin/modules/sccp_manager/sccpManTraits/ajaxHelper.php:731
Stack trace:
#0 /var/www/html/admin/functions.inc.php(118): Whoops\Run->handleError()
#1 /var/www/html/admin/functions.inc.php(118): include()
#2 [internal function]: fpbx_framework_autoloader()
#3 /var/www/html/admin/modules/sccp_manager/Sccp_manager.class.php(85): spl_autoload_call()
#4 /var/www/html/admin/libraries/BMO/Self_Helper.class.php(167): include('/var/www/html/a...')
#5 /var/www/html/admin/libraries/BMO/Self_Helper.class.php(62): FreePBX\Self_Helper->loadObject()
#6 /var/www/html/admin/libraries/modulefunctions.class.php(2565): FreePBX\Self_Helper->injectClass()
#7 /var/www/html/admin/libraries/modulefunctions.class.php(2039): module_functions->_runscripts()
#8 /var/www/html/admin/libraries/Console/Moduleadmin.class.php(444): module_functions->install()
#9 /var/www/html/admi in /var/www/html/admin/modules/sccp_manager/Sccp_manager.class.php on line 85
Whoops\Exception\ErrorException: During class fetch: Uncaught Whoops\Exception\ErrorException: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/admin/modules/sccp_manager/sccpManTraits/ajaxHelper.php:731
Stack trace:
#0 /var/www/html/admin/functions.inc.php(118): Whoops\Run->handleError()
#1 /var/www/html/admin/functions.inc.php(118): include()
#2 [internal function]: fpbx_framework_autoloader()
#3 /var/www/html/admin/modules/sccp_manager/Sccp_manager.class.php(85): spl_autoload_call()
#4 /var/www/html/admin/libraries/BMO/Self_Helper.class.php(167): include('/var/www/html/a...')
#5 /var/www/html/admin/libraries/BMO/Self_Helper.class.php(62): FreePBX\Self_Helper->loadObject()
#6 /var/www/html/admin/libraries/modulefunctions.class.php(2565): FreePBX\Self_Helper->injectClass()
#7 /var/www/html/admin/libraries/modulefunctions.class.php(2039): module_functions->_runscripts()
#8 /var/www/html/admin/libraries/Console/Moduleadmin.class.php(444): module_functions->install()
#9 /var/www/html/admi in file /var/www/html/admin/modules/sccp_manager/Sccp_manager.class.php on line 85
Stack trace:
  1. Whoops\Exception\ErrorException->() /var/www/html/admin/modules/sccp_manager/Sccp_manager.class.php:85
  2. Whoops\Run->handleError() /var/www/html/admin/libraries/Composer/vendor/filp/whoops/src/Whoops/Run.php:383
  3. Whoops\Run->handleShutdown() [internal]:0
Updating Hooks...PHP Fatal error:  During class fetch: Uncaught Whoops\Exception\ErrorException: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/admin/modules/sccp_manager/sccpManTraits/ajaxHelper.php:731

**Comment by sq8mvy** [comment]
Version 14.5.0.3 now installs correctly.
